name: qontact
description: "Qr Code Contact App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  injectable: ^2.1.2
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  easy_localization: ^3.0.7
  auto_route: ^8.1.3
  flutter_svg: ^2.0.10+1
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  shimmer: ^3.0.0
  reactive_forms: ^17.0.1
  reactive_phone_form_field: ^3.0.0
  reactive_date_time_picker: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.2
  freezed: ^2.4.5
  retrofit_generator: ^8.1.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Gellini
      fonts:
        - asset: assets/fonts/Gelline.otf

